version: "3.3"
services:
  ${SERVICE}:
    image: registry.gitlab.com/indev-moph/fiber-api:latest 
    environment:
      - TZ=Asia/Bangkok
      - APP__DEV=false
      - APP__BASEURL=https://indev.moph.go.th/api/v2
      - APP__PORT=80
    volumes:
      - ${SERVICE}_log:/app/logs
    deploy:
      mode: replicated
      replicas: 1      
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.${SERVICE}.tls=true"
        - "traefik.http.routers.${SERVICE}.entrypoints=websecure"
        - "traefik.http.routers.${SERVICE}.rule=Host(`indev.moph.go.th`) && PathPrefix(`/api/v2`)"
        - "traefik.http.services.${SERVICE}.loadbalancer.server.port=80"
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true

volumes:
  ${SERVICE}_log: