# https://taskfile.dev

version: "3"

#### --- Includes --- ####
includes:
  os: ./bin/Taskfile_{{OS}}.yaml

vars:
  APP_NAME: AppName
  APP_VERSION: 0.0.0
  APP_BUILD:
    sh: git log -n 1 --format=%H
  APP_DATE:
    sh: git log -n 1 --format=%aI
  LDFLAGS: -ldflags " -X main.Version={{.APP_VERSION}} -X main.Build={{.APP_BUILD}} -X main.DateBuild={{.APP_DATE}} "

  GO_MAINFILE: main.go
  APP_GMF: gmf
  GO_MODULE:
    sh: go mod why -m | {{.APP_GMF}} stdin -n 1 -r  "^# (.+)\$" "\$1"

tasks:
  default:
    cmds:
      - echo "OS - {{OS}}"
      - task --list-all
    silent: true

  dev:
    cmds:
      - go run {{.LDFLAGS}} {{.GO_MAINFILE}} -c dev.env {{.CLI_ARGS}}

  mod:
    cmds:
      - go mod download
      - go mod tidy
      - go mod vendor

  swag:
    cmds:
      - os:swagger

  swag-prd:
    cmds:
      - os:swagger-prd

  # TODO: Request Tools for Devolopment.
  install-tools:
    cmds:
      - echo "Install `attapon-th/gmf`"
      - go install github.com/attapon-th/gmf/cmd/gmf@latest
      - echo "Install `swaggo/swag`"
      - go install github.com/swaggo/swag/cmd/swag@latest
