# https://taskfile.dev

version: "3"

#### --- Includes --- ####
includes:
  swag: ./bin/Taskfile_swagger.yaml
  tools: ./bin/Taskfile_Tools.yaml
  project: ./bin/Taskfile_project.yaml
  os: ./bin/Taskfile_{{OS}}.yaml

vars:
  APP_NAME: AppName
  APP_VERSION: 0.0.0
  APP_BUILD:
    sh: git log -n 1 --format=%H
  APP_DATE:
    sh: git log -n 1 --format=%aI
  LDFLAGS: -ldflags " -X main.Version={{.APP_VERSION}} -X main.Build={{.APP_BUILD}} -X main.DateBuild={{.APP_DATE}} "

  GO_MAINFILE: main.go
  APP_GMF: gmf
  GO_VERSION:
    sh: go list -m -f \{\{.GoVersion\}\}
  GO_MODULE:
    sh: go list -m -f \{\{.Path\}\}
  DOCKER_REGISTRY_URL: registry.{{.GO_MODULE}}

tasks:
  default:
    cmds:
      - echo "GO Version - {{.GO_VERSION}}"
      - echo "GO Module  - {{.GO_MODULE}}"
      - echo "OS         - {{OS}}"
      - echo "----------"
      - task --list-all
    silent: true

  dev:
    cmds:
      - go run {{.LDFLAGS}} {{.GO_MAINFILE}} -c dev.env {{.CLI_ARGS}}

  mod:
    cmds:
      - go mod download
      - go mod tidy
      - go mod vendor

  swag:
    cmds:
      - task: swag:dev

  swag-prd:
    cmds:
      - task: swag:prd
