version: "3.3"
services:
  ${SERVICE}:
    image: ${IMAGE}:latest 
    environment:
      - TZ=Asia/Bangkok
      - APP.DEV=false
      - APP.BASEURL=https://${DOMAIN}/${PREFIX}
      - APP.PORT=80
      
    volumes:
      - ${SERVICE}_log:/app/logs
    deploy:
      mode: replicated
      replicas: 1      
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.${SERVICE}.tls=true"
        - "traefik.http.routers.${SERVICE}.entrypoints=websecure"
        - "traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN}`) && PathPrefix(`${PREFIX}`)"
        - "traefik.http.services.${SERVICE}.loadbalancer.server.port=80"
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true

volumes:
  ${SERVICE}_log: